# Site settings
title: From Silicon Valley to Silicon Slopes
header-img: img/home-bg.png
email: samecrowder@gmail.com
copyright_name: samecrowder
description: > # this means to ignore newlines until "baseurl:"
  Doubling Down in Computer Science Education
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  samecrowder
learn_profile: samecrowder
email_username: samecrowder@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
